# Site settings
title: plsql.org

description: Website about SQL and PL/SQL Development for Oracle Databases
keywords: oracle, database, SQL, PL/SQL, Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://plsql.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
