# Site settings
title: plsql.info

description: > # this means to ignore newlines until "baseurl:"
  Website for people who studying PL/SQL language for Oracle DataBase
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://plsql.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
